### ISSUE TITLE
Compile on OSX

### ISSUE THREAD

**Issue by Montereytony** [360trev/ME7Sum#3]
My first attempt to compile showed this error:

```
gcc -Wall -O3 -Werror -o load_file.o -c load_file.c
load_file.c:33:10: error: illegal character encoding in string literal [-Werror,-Winvalid-source-encoding]
        printf("<FE> Opening '%s' file\n",filename);
                ^~~~
load_file.c:37:10: error: illegal character encoding in string literal [-Werror,-Winvalid-source-encoding]
        printf("<FE> Getting length of '%s' file\n",filename);
                ^~~~
load_file.c:46:10: error: illegal character encoding in string literal [-Werror,-Winvalid-source-encoding]
        printf("<FE> Allocating buffer of %d bytes\n",size);
                ^~~~

```

If I enter more load_file.c  I see  <FE>, if I  edit the file I see:

printf("þ Opening '%s' file\n",filename);

Do I need to convert special characters?

**Comment by nyetwurk** [comment]
Consider  https://github.com/nyetwurk/ME7Sum instead, this repo is not really updated.

**Comment by Montereytony** [comment]
I ran this command:  perl -pi -e 's/þ /* /g  *  and that fixed the special character that would not compile. All's good now.

Thank you nyetwurk,  I will clone the new repo.
